#> sgp.mineurs:lootdrop/close_detection/schedule
#
# Function that is ran every tick while a lootdrop is opened
# Checks if the contents of the chest change, and reapplies the loot table.
# Scheduled function happens before LootTable is generated by the player.

# Checking if something changed in the chest, if we want to do something with it
# execute store result score #did_something_change sgp.dummy \
    run data modify storage sgp:close_detection Items set from block ~ ~ ~ Items

# Empty LootTable is applied to container after checks.
data modify block ~ ~ ~ LootTable set value "sgp.mineurs:empty"

# Shut off if no players have the container open.
execute if entity @a[tag=sgp.container_open] run function #bs.schedule:schedule {with:{id:"close_detection",command:"execute as @e[type=marker,tag=sgp.marker,name=\"Lootdrop\"] at @s if block ~ ~ ~ trapped_chest run function sgp.mineurs:lootdrop/close_detection/schedule",time:1,unit:"t"}}