scoreboard players set #slot_found dummy 0
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:0}] run function sgp.kits:kills_give/b {slot:0}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:1}] run function sgp.kits:kills_give/b {slot:1}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:2}] run function sgp.kits:kills_give/b {slot:2}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:3}] run function sgp.kits:kills_give/b {slot:3}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:4}] run function sgp.kits:kills_give/b {slot:4}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:5}] run function sgp.kits:kills_give/b {slot:5}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:6}] run function sgp.kits:kills_give/b {slot:6}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:7}] run function sgp.kits:kills_give/b {slot:7}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:8}] run function sgp.kits:kills_give/b {slot:8}

$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:9}] run function sgp.kits:kills_give/b {slot:9}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:10}] run function sgp.kits:kills_give/b {slot:10}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:11}] run function sgp.kits:kills_give/b {slot:11}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:12}] run function sgp.kits:kills_give/b {slot:12}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:13}] run function sgp.kits:kills_give/b {slot:13}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:14}] run function sgp.kits:kills_give/b {slot:14}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:15}] run function sgp.kits:kills_give/b {slot:15}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:16}] run function sgp.kits:kills_give/b {slot:16}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:17}] run function sgp.kits:kills_give/b {slot:17}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:18}] run function sgp.kits:kills_give/b {slot:18}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:19}] run function sgp.kits:kills_give/b {slot:19}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:20}] run function sgp.kits:kills_give/b {slot:20}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:21}] run function sgp.kits:kills_give/b {slot:21}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:22}] run function sgp.kits:kills_give/b {slot:22}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:23}] run function sgp.kits:kills_give/b {slot:23}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:24}] run function sgp.kits:kills_give/b {slot:24}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:25}] run function sgp.kits:kills_give/b {slot:25}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:26}] run function sgp.kits:kills_give/b {slot:26}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:27}] run function sgp.kits:kills_give/b {slot:27}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:28}] run function sgp.kits:kills_give/b {slot:28}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:29}] run function sgp.kits:kills_give/b {slot:29}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:30}] run function sgp.kits:kills_give/b {slot:30}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:31}] run function sgp.kits:kills_give/b {slot:31}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:32}] run function sgp.kits:kills_give/b {slot:32}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:33}] run function sgp.kits:kills_give/b {slot:33}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:34}] run function sgp.kits:kills_give/b {slot:34}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:35}] run function sgp.kits:kills_give/b {slot:35}
