scoreboard players set #slot_found dummy 0
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:0b}] run function sgp.kits:stacking/get_slot_count {slot:0}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:1b}] run function sgp.kits:stacking/get_slot_count {slot:1}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:2b}] run function sgp.kits:stacking/get_slot_count {slot:2}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:3b}] run function sgp.kits:stacking/get_slot_count {slot:3}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:4b}] run function sgp.kits:stacking/get_slot_count {slot:4}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:5b}] run function sgp.kits:stacking/get_slot_count {slot:5}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:6b}] run function sgp.kits:stacking/get_slot_count {slot:6}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:7b}] run function sgp.kits:stacking/get_slot_count {slot:7}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:8b}] run function sgp.kits:stacking/get_slot_count {slot:8}

$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:9b}] run function sgp.kits:stacking/get_slot_count {slot:9}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:10b}] run function sgp.kits:stacking/get_slot_count {slot:10}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:11b}] run function sgp.kits:stacking/get_slot_count {slot:11}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:12b}] run function sgp.kits:stacking/get_slot_count {slot:12}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:13b}] run function sgp.kits:stacking/get_slot_count {slot:13}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:14b}] run function sgp.kits:stacking/get_slot_count {slot:14}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:15b}] run function sgp.kits:stacking/get_slot_count {slot:15}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:16b}] run function sgp.kits:stacking/get_slot_count {slot:16}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:17b}] run function sgp.kits:stacking/get_slot_count {slot:17}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:18b}] run function sgp.kits:stacking/get_slot_count {slot:18}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:19b}] run function sgp.kits:stacking/get_slot_count {slot:19}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:20b}] run function sgp.kits:stacking/get_slot_count {slot:20}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:21b}] run function sgp.kits:stacking/get_slot_count {slot:21}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:22b}] run function sgp.kits:stacking/get_slot_count {slot:22}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:23b}] run function sgp.kits:stacking/get_slot_count {slot:23}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:24b}] run function sgp.kits:stacking/get_slot_count {slot:24}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:25b}] run function sgp.kits:stacking/get_slot_count {slot:25}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:26b}] run function sgp.kits:stacking/get_slot_count {slot:26}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:27b}] run function sgp.kits:stacking/get_slot_count {slot:27}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:28b}] run function sgp.kits:stacking/get_slot_count {slot:28}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:29b}] run function sgp.kits:stacking/get_slot_count {slot:29}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:30b}] run function sgp.kits:stacking/get_slot_count {slot:30}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:31b}] run function sgp.kits:stacking/get_slot_count {slot:31}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:32b}] run function sgp.kits:stacking/get_slot_count {slot:32}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:33b}] run function sgp.kits:stacking/get_slot_count {slot:33}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:34b}] run function sgp.kits:stacking/get_slot_count {slot:34}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:35b}] run function sgp.kits:stacking/get_slot_count {slot:35}
$execute as @s unless score #slot_found dummy matches 1 if data entity @s Inventory[{id:"minecraft:$(item_id)", Slot:99b}] run function sgp.kits:stacking/get_slot_count {slot:99}
