scoreboard players enable @s veut_light
scoreboard players enable @s veut_medium
scoreboard players enable @s veut_heavy
scoreboard players enable @s veut_super_heavy
scoreboard players enable @s veut_flame_crown
scoreboard players enable @s veut_cloud
scoreboard players enable @s veut_marine
scoreboard players enable @s veut_smoke
scoreboard players enable @s veut_ench
scoreboard players enable @s veut_desactiver
scoreboard players enable @s sort_cosm
scoreboard players enable @s veut_kill_anvil
scoreboard players enable @s veut_kill_explosion
scoreboard players enable @s veut_kill_portal
scoreboard players enable @s veut_kill_witch
scoreboard players enable @s veut_kill_hurt
scoreboard players enable @s veut_kill_cloud
scoreboard players enable @s veut_kill_splash
scoreboard players enable @s veut_kill_firework
scoreboard players enable @s veut_kill_random
scoreboard players enable @s veut_kill_disabled