#> sgp.world:lieu/loop/4
# `{uuid: string, data: compound}`: the head of sgp:data temp.lieu.list.
# Shard 4 of 8 (generated by the location loop generator; all shards are identical apart
# from their successor). Markers 4, 12, ... run through this file, so its macro cache
# only ever holds their uuids. A marker that vanished since registration simply fails the
# `execute as` and the loop moves on.
$execute as $(uuid) at @s run function sgp.world:lieu/scan/4 with storage sgp:data temp.lieu.list[0].data
data remove storage sgp:data temp.lieu.list[0]
execute if data storage sgp:data temp.lieu.list[0] run function sgp.world:lieu/loop/5 with storage sgp:data temp.lieu.list[0]
