execute as @s run trigger veut_light set 0
execute as @s run trigger veut_medium set 0
execute as @s run trigger veut_heavy set 0
execute as @s run trigger veut_super_heavy set 0
execute as @s run trigger veut_flame_crown set 0
execute as @s run trigger veut_cloud set 0
execute as @s run trigger veut_marine set 0
execute as @s run trigger veut_smoke set 0
execute as @s run trigger veut_ench set 0
execute as @s run trigger veut_desactiver set 0
execute as @s run trigger veut_kill_anvil set 0
execute as @s run trigger veut_kill_explosion set 0
execute as @s run trigger veut_kill_portal set 0
execute as @s run trigger veut_kill_witch set 0
execute as @s run trigger veut_kill_hurt set 0
execute as @s run trigger veut_kill_cloud set 0
execute as @s run trigger veut_kill_splash set 0
execute as @s run trigger veut_kill_firework set 0
execute as @s run trigger veut_kill_random set 0
execute as @s run trigger veut_kill_disabled set 0