title @a title [{"text":"Le ","bold":true},{"text":"Canarchimage","color":"dark_purple"},{"text":" est revenu !"}]
tellraw @a [{"text":"Canarchimage : ","color":"dark_purple","bold": true},{"text":"Haha ! Je suis venu me venger de l'humiliation que j'ai subie lors de la 1ère édition !","color":"white","bold": false}]
tellraw @a [{"text":"Canarchimage : ","color":"dark_purple","bold": true},{"text":"J'ai réussi à créer un sort pour me transformer en véritable Canard !","color":"white","bold": false}]
tellraw @a [{"text":"Canarchimage : ","color":"dark_purple","bold": true},{"text":"Tu ne peux donc plus simplement dire que je suis un furry et non un vrai canard. Moi aussi je suis désormais Label Rouge, Élevé en Plein Air !","color":"white","bold": false}]
tellraw @a [{"text":"Canarchimage : ","color":"dark_purple","bold": true},{"text":"J'ai transformé ta statue en une toute nouvelle statue en mon honneur, mouahahaha...","color":"white","bold": false}]
tellraw @a [{"text":"Le Grand Poulet : ","color":"dark_blue","bold": true},{"text":"Je ne te laisserai pas faire !","color":"white","bold": false}]
tellraw @a [{"text":"Canarchimage : ","color":"dark_purple","bold": true},{"text":"Et tu comptes faire quoi exactement ? J'ai mis une barrière protectrice autour !","color":"white","bold": false}]
tellraw @a [{"text":"Le Grand Poulet : ","color":"dark_blue","bold": true},{"text":"Argh ! Je la détruirai !","color":"white","bold": false}]
tellraw @a [{"text":"Le Grand Poulet : ","color":"dark_blue","bold": true},{"text":"Kamé Hamé Ha !","color":"white","bold": false}]
tellraw @a [{"text":"Le Grand Poulet : ","color":"dark_blue","bold": true},{"text":"Ouah c'est fatiguant... Et puis ça me donne faim... Il me faut manger avant de pouvoir recommencer.","color":"white","bold": false}]
title @a subtitle "Vous avez toute la Soirée pour trouver comment faire"
title @a title [{"text":"Nourrissez "},{"text":"Le Grand Poulet !","color":"dark_blue","bold": true}]