clear @s
effect clear @s
item replace entity @s hotbar.0 with stone_sword{Unbreakable:1, AttributeModifiers:[{AttributeName:"generic.attack_damage", Name:"Damage", Slot:"mainhand", Amount:5.0d, Operation:0, UUID:[I; -124310, 13101, 13111, -26202]}, {Slot:"mainhand", AttributeName:"generic.attack_speed", Name:"generic.attack_speed", Amount:1000.0d, Operation:0, UUID:[I; -110663, 103297, -1423577, 206238]}], Enchantments:[{id:"sharpness", lvl:1}], HideFlags:63, display:{Name:'{"text":"Épée en Pierre", "color":"light_purple", "italic":false, "bold":true}', Lore:['{"text":"---------------", "color":"#C0C0C0", "italic":false}', '{"text":"⚔ Tranchant I", "color":"dark_red", "italic":false}', '{"text":"6 dégats", "color":"blue", "italic":false}']}}
item replace entity @s weapon.offhand with baked_potato{display:{Name:'{"text":"Pommes de Terre cuites au Four", "color":"light_purple", "italic":false, "bold":true}', Lore:['[{"text":"Régénère jusqu\'à 3", "color":"gray", "italic":false}, {"text":"❤", "color":"red", "italic":false}]']}} 64
item replace entity @s hotbar.3 with splash_potion{Potion:"water", custom_potion_effects:[{id:"blindness", amplifier:0, duration:100}], HideFlags:63, display:{Name:'{"text":"Potion de Cécité", "color":"light_purple", "italic":false, "bold":true}', Lore:['{"text":"----------------", "color":"#C0C0C0", "italic":false}', '{"text":"👁 Cécité (0:05)", "color":"#8B8589", "italic":false}']}}
item replace entity @s hotbar.4 with milk_bucket{display:{Name:'{"text":"Antibiotique", "color":"light_purple", "italic":false, "bold":true}', Lore:['[{"text":"Enlève tous les effets", "color":"gray", "italic":false}]']}}
item replace entity @s armor.head with chainmail_helmet{Trim:{pattern:tide, material:amethyst}, Unbreakable:1, Enchantments:[{id:"protection", lvl:1}], HideFlags:255, display:{Name:'{"text":"Casque de Mailles", "color":"light_purple", "italic":false, "bold":true}', Lore:['{"text":"------------------", "color":"#C0C0C0", "italic":false}', '{"text":"🛡 Protection I", "color":"dark_aqua", "italic":false}']}}
item replace entity @s armor.chest with chainmail_chestplate{Trim:{pattern:sentry, material:amethyst}, Unbreakable:1, Enchantments:[{id:"protection", lvl:1}, {id:"projectile_protection", lvl:2}], HideFlags:255, display:{Name:'{"text":"Cotte de Mailles", "color":"light_purple", "italic":false, "bold":true}', Lore:['{"text":"----------------", "color":"#C0C0C0", "italic":false}', '{"text":"🛡 Protection I", "color":"dark_aqua", "italic":false}', '{"text":"➹ Protection II", "color":"dark_blue", "italic":false}']}}
item replace entity @s armor.legs with chainmail_leggings{Trim:{pattern:sentry, material:amethyst}, Unbreakable:1, Enchantments:[{id:"protection", lvl:1}], HideFlags:255, display:{Name:'{"text":"Jambières de Mailles", "color":"light_purple", "italic":false, "bold":true}', Lore:['{"text":"--------------------", "color":"#C0C0C0", "italic":false}', '{"text":"🛡 Protection I", "color":"dark_aqua", "italic":false}']}}
item replace entity @s armor.feet with chainmail_boots{Trim:{pattern:sentry, material:amethyst}, Unbreakable:1, Enchantments:[{id:"protection", lvl:1}], HideFlags:255, display:{Name:'{"text":"Bottes de Mailles", "color":"light_purple", "italic":false, "bold":true}', Lore:['{"text":"-----------------", "color":"#C0C0C0", "italic":false}', '{"text":"🛡 Protection I", "color":"dark_aqua", "italic":false}']}}
tag @s add alchimiste_voulu
scoreboard players set @s reset_tags 1
scoreboard players set @s kit_id 8
item replace entity @s hotbar.1 from entity @e[type=armor_stand,name="alchimiste_potion_stacker",limit=1] weapon.mainhand
item replace entity @s hotbar.2 from entity @e[type=armor_stand,name="alchimiste_potion_stacker",limit=1] weapon.offhand
scoreboard players set @s veut_alchimiste 0
scoreboard players set @s kitPrefixSet 0