execute as @s run trigger spawn_1 set 0
execute as @s run trigger spawn_2 set 0
execute as @s run trigger spawn_3 set 0
execute as @s run trigger spawn_4 set 0
execute as @s run trigger spawn_5 set 0
execute as @s run trigger spawn_6 set 0
execute as @s run trigger spawn_7 set 0
execute as @s run trigger spawn_8 set 0
execute as @s run trigger spawn_9 set 0
execute as @s run trigger spawn_10 set 0
execute as @s run trigger spawn_11 set 0
execute as @s run trigger spawn_random set 0
execute as @s run trigger spawn_vers_kits set 0