scoreboard players enable @s spawn1
scoreboard players enable @s spawn2
scoreboard players enable @s spawn3
scoreboard players enable @s spawn4
scoreboard players enable @s spawn5
scoreboard players enable @s spawn6
scoreboard players enable @s spawn7
scoreboard players enable @s spawn8
scoreboard players enable @s spawn9
scoreboard players enable @s spawn10
scoreboard players enable @s spawn11
scoreboard players enable @s spawn_random
scoreboard players enable @s spawn_vers_kits