execute as @s run trigger sgp.spawn_1 set 0
execute as @s run trigger sgp.spawn_2 set 0
execute as @s run trigger sgp.spawn_3 set 0
execute as @s run trigger sgp.spawn_4 set 0
execute as @s run trigger sgp.spawn_5 set 0
execute as @s run trigger sgp.spawn_6 set 0
execute as @s run trigger sgp.spawn_7 set 0
execute as @s run trigger sgp.spawn_8 set 0
execute as @s run trigger sgp.spawn_9 set 0
execute as @s run trigger sgp.spawn_10 set 0
execute as @s run trigger sgp.spawn_11 set 0
execute as @s run trigger sgp.spawn_random set 0
execute as @s run trigger sgp.spawn_vers_kits set 0