scoreboard players enable @s spawn_1
scoreboard players enable @s spawn_2
scoreboard players enable @s spawn_3
scoreboard players enable @s spawn_4
scoreboard players enable @s spawn_5
scoreboard players enable @s spawn_6
scoreboard players enable @s spawn_7
scoreboard players enable @s spawn_8
scoreboard players enable @s spawn_9
scoreboard players enable @s spawn_10
scoreboard players enable @s spawn_11
scoreboard players enable @s spawn_random
scoreboard players enable @s spawn_vers_kits