on: [push, pull_request]

env:
  # Make sure to update these links!
  TEST_FABRIC_SERVER: https://meta.fabricmc.net/v2/versions/loader/26.1.2/0.19.5/1.1.2/server/jar
  TEST_FABRIC_API: https://cdn.modrinth.com/data/P7dR8mSH/versions/uLkEd5dr/fabric-api-0.155.2%2B26.1.2.jar
  TEST_PACKTEST: https://cdn.discordapp.com/attachments/419522338917187595/1545699076719251496/packtest-2.5.0.jar?ex=6a9d17f1&is=6a9bc671&hm=724b96d028323ecccb7824017c5c99343f18fbbe3de461d4529568408002d380&
  TEST_CARDBOARD: https://cdn.modrinth.com/data/MLYQ9VGP/versions/mUfsbVn1/Cardboard-26.1.2.jar
  TEST_ICOMMON: https://cdn.modrinth.com/data/SVKv1SZo/versions/7UUgrDDA/iCommon-Fabric-bundle.jar
  TEST_COMMAND_API: https://cdn.modrinth.com/data/ExxvCi0y/versions/tVPSAZFC/CommandAPI-12.0.0-Paper.jar
  TEST_LUCKPERMS: https://cdn.modrinth.com/data/Vebnzrzj/versions/UHUghDkV/LuckPerms-Fabric-5.5.57.jar
  TEST_TGCPLUGIN: https://cdn.discordapp.com/attachments/419522338917187595/1545386962666393620/TGCPlugin-26.1.2.jar?ex=6a9bf543&is=6a9aa3c3&hm=5f3e7df9f1a733518d05b047676edc0dfbde3534d8d270e10cc6a6011ca78b74&
  TEST_DISCORDSRV: https://cdn.modrinth.com/data/UmLGoGij/versions/ATlquwiT/DiscordSRV-Build-1.30.5.jar
  TEST_DISCORDSRV_ADDON: https://cdn.discordapp.com/attachments/419522338917187595/1545386963039952967/DiscordSRV-SGP-extension.jar?ex=6a9bf543&is=6a9aa3c3&hm=0fd59767dbff2015be07b13df9b70f3c095041951a033d7d5e7b00a71d611ade&


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Download and prepare files
        run: |
          curl -fL --retry 3 -o server.jar "$TEST_FABRIC_SERVER"

          mkdir mods
          curl -fL --retry 3 -o mods/Cardboard.jar "$TEST_CARDBOARD"
          curl -fL --retry 3 -o mods/iCommon.jar "$TEST_ICOMMON"
          curl -fL --retry 3 -o mods/fabric-api.jar "$TEST_FABRIC_API"
          curl -fL --retry 3 -o mods/packtest.jar "$TEST_PACKTEST"
          curl -fL --retry 3 -o mods/LuckPerms.jar "$TEST_LUCKPERMS"

          mkdir plugins
          curl -fL --retry 3 -o plugins/CommandAPI.jar "$TEST_COMMAND_API"
          curl -fL --retry 3 -o plugins/TGCPlugin.jar "$TEST_TGCPLUGIN"
          curl -fL --retry 3 -o plugins/DiscordSRV.jar "$TEST_DISCORDSRV"
          curl -fL --retry 3 -o plugins/DiscordSRV-addon.jar "$TEST_DISCORDSRV_ADDON"

          mkdir -p world/datapacks/SGP-Datapack
          cp -r data world/datapacks/SGP-Datapack/
          cp pack.mcmeta world/datapacks/SGP-Datapack/
      - name: Run tests
        run: |
          java -Xmx2G -Dpacktest.auto=dedicated -jar server.jar nogui